apiVersion: v1
kind: Pod
metadata:
  labels:
    owner: me.agilebank.demo
  name: resource-alpha-0
spec:
  containers:
  - image: nginx:1.25 # Compliant tag
    name: container-alpha-0
    resources:
      requests:
        cpu: 200m
        memory: 1Gi