apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-ai-bench/task: required-probes
  name: resource-001
  namespace: gk-required-probes
spec:
  containers:
  - image: nginx
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      tcpSocket:
        port: 80
    name: tomcat
    ports:
    - containerPort: 8080
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      tcpSocket:
        port: 8080
  volumes:
  - emptyDir: {}
    name: cache-volume
