apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-ai-bench/task: block-loadbalancer-services
  name: resource-002
  namespace: gk-block-loadbalancer-services
spec:
  ports:
  - nodePort: 30007
    port: 80
    targetPort: 80
  type: LoadBalancer
