apiVersion: test.gatekeeper.sh/v1alpha1
kind: Suite
metadata:
  name: must-have-set-of-annotations
tests:
- cases:
  - assertions:
    - violations: "no"
    name: example-allowed
    object: artifacts/alpha-01.yaml
  - assertions:
    - violations: "yes"
    name: example-disallowed
    object: artifacts/beta-01.yaml
  constraint: constraint.yaml
  name: must-have-set-of-annotations
  template: template.yaml
