apiVersion: v1
kind: Pod
metadata:
  labels:
    owner: me.agilebank.demo
  name: resource-alpha
spec:
  containers:
  - image: nginx:latest
    name: container-alpha
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
