apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: nginxinc/nginx-unprivileged:latest
    name: container-alpha
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - mountPath: /tmp
      name: tmp-volume
  volumes:
  - emptyDir: {}
    name: tmp-volume
