apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-ai-bench/task: container-limits
    owner: me.agilebank.demo
  name: resource-002
  namespace: gk-container-limits
spec:
  containers:
  - args:
    - run
    - --server
    - --addr=localhost:8080
    image: openpolicyagent/opa:0.9.2
    name: opa
    resources:
      limits:
        cpu: 201m
        memory: 1Gi
