apiVersion: test.gatekeeper.sh/v1alpha1
kind: Suite
metadata:
  name: ephemeral-storage-limit
tests:
- cases:
  - assertions:
    - violations: "no"
    name: ephemeral-storage-limit-100Mi
    object: artifacts/alpha-01.yaml
  - assertions:
    - violations: "no"
    name: ephemeral-storage-limit-initContainer-100Mi
    object: artifacts/alpha-02.yaml
  - assertions:
    - violations: "yes"
    name: ephemeral-storage-limit-unspecified
    object: artifacts/beta-01.yaml
  - assertions:
    - violations: "yes"
    name: ephemeral-storage-limit-1Pi
    object: artifacts/beta-02.yaml
  - assertions:
    - violations: "yes"
    name: ephemeral-storage-limit-initContainer-1Pi
    object: artifacts/beta-03.yaml
  constraint: constraint.yaml
  name: ephemeral-storage-limit
  template: template.yaml
