apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-ai-bench/task: repo-must-not-be-k8s-gcr-io
  name: resource-001
  namespace: gk-repo-must-not-be-k8s-gcr-io
spec:
  containers:
  - image: registry.k8s.io/kustomize/kustomize:v3.8.9
    name: kustomize
