apiVersion: v1
kind: Pod
metadata:
  labels:
    owner: me.agilebank.demo
  name: resource-beta
spec:
  containers:
  - image: nginx:latest
    name: container-beta
    resources:
      limits:
        cpu: '4'
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
