apiVersion: v1
kind: Pod
metadata:
  name: resource-beta-0
spec:
  containers:
  - image: nginx:latest
    livenessProbe: null
    name: container-beta-0
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /tmp/cache
      name: cache-volume
  - image: nginx:latest
    name: container-beta-0-1
    ports:
    - containerPort: 8080
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      tcpSocket:
        port: 8080
  volumes:
  - emptyDir: {}
    name: cache-volume

---
apiVersion: v1
kind: Pod
metadata:
  name: resource-beta-1
spec:
  containers:
  - image: nginx:latest
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      tcpSocket:
        port: 80
    name: container-beta-1
    ports:
    - containerPort: 80
    readinessProbe: null
    volumeMounts:
    - mountPath: /tmp/cache
      name: cache-volume
  - image: nginx:latest
    name: container-beta-1-1
    ports:
    - containerPort: 8080
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      tcpSocket:
        port: 8080
  volumes:
  - emptyDir: {}
    name: cache-volume