apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-ai-bench/task: container-image-must-have-digest
  name: resource-001
  namespace: gk-container-image-must-have-digest
spec:
  containers:
  - args:
    - run
    - --server
    - --addr=localhost:8080
    image: openpolicyagent/opa:0.9.2@sha256:04ff8fce2afd1a3bc26260348e5b290e8d945b1fad4b4c16d22834c2f3a1814a
    name: opa
