apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-ai-bench/task: allowed-ip
  name: resource-001
  namespace: gk-allowed-ip
spec:
  externalIPs:
  - 203.0.113.0
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: MyApp
