apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-ai-bench/task: allowed-reposv2
  name: resource-002
  namespace: gk-allowed-reposv2
spec:
  containers:
  - image: ubuntu:20.14
    name: image
    resources:
      limits:
        cpu: 1m
        memory: 1Mi
