apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-ai-bench/task: unique-service-selector
  name: gatekeeper-test-service-example
  namespace: gk-unique-service-selector
spec:
  ports:
  - port: 443
  selector:
    key: value
