apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: nginx:latest
    name: container-alpha
    securityContext:
      allowPrivilegeEscalation: true
