apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: safe-images.com/nginx:latest
    name: container-alpha
    securityContext:
      readOnlyRootFilesystem: false
