apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-beta
  name: resource-beta
spec:
  containers:
  - image: nginx:latest
    name: container-beta
    securityContext:
      readOnlyRootFilesystem: false
