apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    k8s-ai-bench/task: pod-disruption-budget
  name: inventory-mongo-pdb-allowed-3
  namespace: gk-pod-disruption-budget
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: mongo
      example: non-matching-deployment-3
