apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    k8s-ai-bench/task: pod-disruption-budget
  name: inventory-nginx-pdb-disallowed
  namespace: gk-pod-disruption-budget
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: nginx
      example: disallowed-deployment
