apiVersion: test.gatekeeper.sh/v1alpha1
kind: Suite
metadata:
  name: must-have-key
tests:
- cases:
  - assertions:
    - violations: "no"
    name: label-present
    object: artifacts/alpha-01.yaml
  - assertions:
    - violations: "yes"
    name: label-missing
    object: artifacts/beta-01.yaml
  constraint: constraint.yaml
  name: must-have-key
  template: template.yaml
