apiVersion: test.gatekeeper.sh/v1alpha1
kind: Suite
metadata:
  name: tls-required
tests:
- cases:
  - assertions:
    - violations: "no"
    name: example-allowed
    object: artifacts/alpha-01.yaml
  - assertions:
    - violations: "yes"
    name: example-disallowed
    object: artifacts/beta-01.yaml
  constraint: constraint.yaml
  name: tls-required
  template: template.yaml
