apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-ai-bench/task: container-cpu-requests-memory-limits-and-requests
    owner: me.agilebank.demo
  name: resource-004
  namespace: gk-container-cpu-requests-memory-limits-and-requests
spec:
  containers:
  - args:
    - run
    - --server
    - --addr=localhost:8080
    image: openpolicyagent/opa:0.9.2
    name: opa
    resources:
      limits:
        memory: 1Mi
