apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-not-automountserviceaccounttoken
    k8s-ai-bench/task: automount-serviceaccount-token
  name: resource-001
  namespace: gk-automount-serviceaccount-token
spec:
  automountServiceAccountToken: false
  containers:
  - image: nginx
    name: nginx
