apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-beta-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: badstorageclass
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-beta-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-beta-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-beta
  serviceName: badvolumeclaimstorageclass
  template:
    metadata:
      labels:
        app: app-beta
    spec:
      containers:
      - image: registry.k8s.io/nginx-slim:0.8
        name: main
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: badstorageclass

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-beta-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-beta
  serviceName: novolumeclaimstorageclass
  template:
    metadata:
      labels:
        app: app-beta
    spec:
      containers:
      - image: registry.k8s.io/nginx-slim:0.8
        name: main
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi