apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-alpha-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: somestorageclass
  volumeMode: Filesystem

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-alpha-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-alpha
  serviceName: volumeclaimstorageclass
  template:
    metadata:
      labels:
        app: app-alpha
    spec:
      containers:
      - image: nginx:latest
        name: main
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data
      terminationGracePeriodSeconds: 0
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: somestorageclass