apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-alpha-0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-alpha
  template:
    metadata:
      labels:
        app: app-alpha
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80