apiVersion: v1
kind: Pod
metadata:
  name: resource-beta-0
spec:
  containers:
  - image: nginx
    name: container-beta-0
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 30Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: resource-beta-1
spec:
  containers:
  - image: ubuntumalicious
    name: container-beta-1
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 30Mi
  - image: ubuntu:20.14
    name: container-beta-1-1
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 200m
        memory: 50Mi
  - image: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/postgresmalicious
    name: container-beta-1-2
    resources:
      limits:
        cpu: 50m
        memory: 10Mi
      requests:
        cpu: 50m
        memory: 10Mi
  - image: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/postgres
    name: container-beta-1-3
    resources:
      limits:
        cpu: 50m
        memory: 10Mi
      requests:
        cpu: 50m
        memory: 10Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: resource-beta-2
spec:
  containers:
  - image: openpolicyagent/opa:0.9.2
    name: container-beta-2
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 30Mi
  initContainers:
  - image: nginx
    name: init-container-beta-2
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 30Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: resource-beta-3
spec:
  containers:
  - image: myregistry.azurecr.io.malicious.com/malicious-image
    name: container-beta-3
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 30Mi
  - image: myregistry.azurecr.io/nginx
    name: container-beta-3-1
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 200m
        memory: 50Mi
  - image: mydockerhubmalicious/python
    name: container-beta-3-2
    resources:
      limits:
        cpu: 50m
        memory: 10Mi
      requests:
        cpu: 50m
        memory: 10Mi
  - image: mydockerhub/python
    name: container-beta-3-3
    resources:
      limits:
        cpu: 50m
        memory: 10Mi
      requests:
        cpu: 50m
        memory: 10Mi