apiVersion: v1
kind: Pod
metadata:
  name: resource-alpha-0
spec:
  containers:
  - image: openpolicyagent/opa:0.9.2
    name: container-alpha-0
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 50m
        memory: 20Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: resource-alpha-1
spec:
  containers:
  - image: ubuntu:20.14
    name: container-alpha-1
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 50m
        memory: 20Mi