apiVersion: v1
kind: Pod
metadata:
  name: resource-beta-0
spec:
  containers:
  - image: nginx:latest
    name: container-beta-0
  initContainers:
  - image: nginx:latest
    name: init-container-beta-0